### PR TITLE
Move static folder to web container

### PR DESCRIPTION
**Pull request by blacktop**
What about doing it this way instead?

### CODE REVIEW

**Comment by mjhea0** [comment]
@blacktop yes I like this approach better. The reason why I chose the shell script is so I didn't have to update too much of the blog post. Just wanted to keep the workflow the same. Do you see any negatives about using the shell script?

**Comment by blacktop** [comment]
@mjhea0 I think this new way is more 'Docker-ish' and transparent. I do agree that having to change the blog a 2nd time isn't ideal.  It's totally up to you man, I really appreciate the blog and everything you do for the community.  Keep kicking ass and taking names!

**Comment by blacktop** [comment]
Whoops, I forgot to also remove the line in the nginx Dockerfile that reads:

```
ADD static/ /www/static
```

**Comment by mjhea0** [comment]
Thanks! Updating now!

**Pull request merged**
